version: "3.9"

services:
  test-app:
    profiles: ["main"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: ${UID}
    image: test-app:latest
    container_name: test-app-container
    volumes:
      - ./:/var/www/html:delegated
      - ./docker-configs/php.ini:/usr/local/etc/php/php.ini:ro
      - ./example_dir:/home/app/uploading_files #Test uploading files will be mounted here
    ports:
      - 8000:80
      - 5173:5173 #Vite Port
    depends_on:
      - test-mariadb

  test-redis-server:
    profiles: ["main"]
    image: "redis:alpine"
    command: redis-server
    container_name: test-redis-server-container
    ports:
      - "6379:6379"

  test-mariadb:
    profiles: ["main"]
    image: mariadb:10.8.3
    container_name: test-mariadb
    command:
      [
        '--default-time-zone=+00:00',
        '--default-authentication-plugin=mysql_native_password'
      ]
    ports:
      - 3308:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - test-mariadb-data:/var/lib/mysql

  test-phpmyadmin:
    profiles: ["main"]
    image: phpmyadmin/phpmyadmin:latest
    container_name: test-phpmyadmin
    environment:
      - PMA_HOST=test-mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=120M
    ports:
      - "6001:80"
    depends_on:
      - test-mariadb

  test-mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
    - 1025:1025
    - 8003:8025

  test-docs:
    profiles: ["main"]
    image: nginx
    container_name: test-docs-container
    ports:
      - 6004:80
    volumes:
      - ./docs:/usr/share/nginx/html

volumes:
  test-mariadb-data:
